- name: Add PPA
  apt_repository:
    repo: "{{ item }}"
  with_items: "{{ qt53_apt_ppas }}"

- name: install APT packages
  apt:
    name: "{{ item }}"
    update_cache: yes
    state: latest
    cache_valid_time: 86400
  with_items: "{{ qt53_apt_packages }}"

- name: Copy Prepare Script
  template:
    src: 'qt53.sh.j2'
    dest: "{{ buildbot_worker_prepare_dir }}/{{ qt53_tag }}.sh"
    owner: '{{ buildbot_worker_user }}'
    group: '{{ buildbot_worker_user }}'
    mode: 'u+x'

- name: Store Facts
  set_fact:
    buildbot_worker_setups: "{{ buildbot_worker_setups }} + ['{{ qt53_tag }}']"
  tags: [always]
