- name: setup master
  hosts: buildbot-master
  become: yes
  roles:
  - hicknhack-software.buildbot/master/install
  - hicknhack-software.buildbot/master/create
  - hicknhack-software.buildbot/master/inplace-config
  - role: hicknhack-software.buildbot/project/add
    project_name: 'Twofold-Qt'
    project_repo_url: 'https://github.com/hicknhack-software/Twofold-Qt.git'
  tags:
  - master

- name: setup workers
  hosts: buildbot-workers
  become: yes
  roles:
  - hicknhack-software.buildbot/worker/create
  - example-setups/qt53
  - example-setups/gcc49
  - example-setups/qt53_gcc49
  - hicknhack-software.buildbot/worker/configure
  tags:
  - worker

- name: setup winworkers
  hosts: buildbot-winworkers
  pre_tasks:
  - name: Fetch Path
    raw: "Write-Host $env:Path"
    register: buidbot_winworker_path
    changed_when: no

  - name: Exclude OpenSSH from Path
    win_environment:
      name: "Path"
      level: "machine"
      value: "{{ buidbot_winworker_path.stdout_lines[0] | regex_replace(';[^;]*\\\\OpenSSH\\\\[^;]*(;?)', '\\1') }}"

  - name: Unset CYGWIN
    win_environment:
      name: "CYGWIN"
      level: "machine"
      state: absent

  roles:
  - hicknhack-software.buildbot/winworker/create
  - example-setups/qt54_mingw491
  - hicknhack-software.buildbot/winworker/configure
  tags:
  - winworker

- name: start master
  hosts: buildbot-master
  gather_facts: no
  become: yes
  roles:
  - hicknhack-software.buildbot/master/start-inplace
  tags:
  - master

- name: start workers
  hosts: buildbot-workers
  gather_facts: no
  become: yes
  roles:
  - hicknhack-software.buildbot/worker/start
  tags:
  - worker

- name: start winworkers
  hosts: buildbot-winworkers
  gather_facts: no
  roles:
  - hicknhack-software.buildbot/winworker/start
  tags:
  - winworker
