---
- name: icu | Directory
  win_file:
    path: "{{ qt_icu_dir }}"
    state: directory

- name: icu | Download
  win_get_url:
    url: '{{ qt_icu_url }}'
    dest: '{{ qt_icu_archive }}'
    force: no
  register: qt_icu_download_result

- name: icu | Extract
  raw: '7za x -aoa -o"{{ qt_dir }}" "{{ qt_icu_archive }}"'
  when: qt_icu_download_result.changed
